import { Project, Equipment, OrgNode } from './types';

export const projects: Project[] = [
  {
    id: 1,
    nameAr: "مشروع مركز الرياض الدولي للمؤتمرات والمعارض",
    nameEn: "Riyadh International Convention & Exhibition Center",
    clientAr: "غرفة الرياض",
    clientEn: "Riyadh Chamber of Commerce and Industry",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 8900000,
    durationAr: "سنة وشهراً واحداً",
    durationEn: "1 Year, 1 Month",
    startDate: "2018-01",
    completionDate: "2019-02",
    progress: 100,
    scopeAr: "أعمال الحفريات والتربة لمبنى فندق راديسون بلو.",
    scopeEn: "Excavation work for the Radisson Hotel building.",
    category: 'excavation'
  },
  {
    id: 2,
    nameAr: "بطولة العالم للفورمولا وان",
    nameEn: "Formula One World Championship",
    clientAr: "موسم الدرعية",
    clientEn: "Diriyah Season",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 22963410,
    durationAr: "سنة و 5 أشهر",
    durationEn: "1 Year, 5 Months",
    startDate: "2018-10",
    completionDate: "2020-03",
    progress: 100,
    scopeAr: "إعادة سفلتة حلبة السباق وتوريد الحواجز والصدادات الأمنية.",
    scopeEn: "Resurfacing of the Race Track & Supply of Barriers.",
    category: 'roads'
  },
  {
    id: 3,
    nameAr: "مشروع تمهيد ورصف مواقف السيارات بالدرعية",
    nameEn: "Parking Lot Leveling & Paving Project in Diriyah",
    clientAr: "موسم الدرعية",
    clientEn: "Diriyah Season",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 16101000,
    durationAr: "سنة وشهراً واحداً",
    durationEn: "1 Year, 1 Month",
    startDate: "2019-01",
    completionDate: "2020-02",
    progress: 100,
    scopeAr: "أعمال التمهيد الترابية وتعبيد الأسفلت وتسوية المناسيب.",
    scopeEn: "Earthworks & Asphalt paving, and leveling.",
    category: 'roads'
  },
  {
    id: 4,
    nameAr: "مشروع ايكيا الرياض",
    nameEn: "Ikea",
    clientAr: "شركة نسما وشركاهم",
    clientEn: "Nesma & Partners",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 9000000,
    durationAr: "سنة و 6 أشهر",
    durationEn: "1 Year, 6 Months",
    startDate: "2020-01",
    completionDate: "2021-07",
    progress: 100,
    scopeAr: "تجهيز الموقع (أعمال الحفريات والردم)، رصف وتخطيط مواقف السيارات، وأعمال أعمدة الإنارة والكهرباء.",
    scopeEn: "Site Preparation (Excavation & Backfill), Paving Marking Areas, Parking Area & Electric Pole Works.",
    category: 'infrastructure'
  },
  {
    id: 5,
    nameAr: "مشروع أعمال الطرق لأحياء شمال الرياض",
    nameEn: "Road Works Project for North Riyadh Districts",
    clientAr: "أمانة منطقة الرياض",
    clientEn: "Riyadh Municipality",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 12600000,
    durationAr: "سنة وشهراً واحداً",
    durationEn: "1 Year, 1 Month",
    startDate: "2019-08",
    completionDate: "2020-09",
    progress: 100,
    scopeAr: "أعمال الرصف وتعبيد الطرق بالأسفلت في منطقتي بنبان والفيحاء.",
    scopeEn: "Asphalt Paving in Al-Banban & Al-Ridh Dist.",
    category: 'roads'
  },
  {
    id: 6,
    nameAr: "تحسين المشهد الحضري على امتداد مخارج الطرق في جنوب وغرب الرياض",
    nameEn: "Improving the urban Landscape along the Road exits at South & West of Riyadh",
    clientAr: "أمانة منطقة الرياض",
    clientEn: "Riyadh Municipality",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 77980000,
    durationAr: "سنتان و 9 أشهر",
    durationEn: "2 Year, 9 Months",
    startDate: "2020-05",
    completionDate: "2023-02",
    progress: 100,
    scopeAr: "أعمال الأسفلت، الأرصفة والبردورات، تركيب أعمدة الإنارة الديكورية، وتشجير الممرات.",
    scopeEn: "Asphalt, Sidewalks, Light Poles, & Tree Planting.",
    category: 'roads'
  },
  {
    id: 7,
    nameAr: "مشروع تحويل مسار السكك الحديدية بالهفوف",
    nameEn: "Railway Diversion project",
    clientAr: "المؤسسة العامة للخطوط الحديدية",
    clientEn: "General Railway Corporation",
    locationAr: "الهفوف",
    locationEn: "Al-Hofuf",
    valueSAR: 84500000,
    durationAr: "سنة و 10 أشهر",
    durationEn: "1 Year, 10 Months",
    startDate: "2020-06",
    completionDate: "2022-04",
    progress: 100,
    scopeAr: "الأعمال الترابية من صخر وقطع وردم وتسوية جدار الحماية الحجري.",
    scopeEn: "Earthworks (Cutting, Backfilling, Stone Works).",
    category: 'infrastructure'
  },
  {
    id: 8,
    nameAr: "مشروع مخطط حي القيروان",
    nameEn: "Al Qairawan District, Plan Project",
    clientAr: "شركة الأكاسيا العقارية",
    clientEn: "Acacia Real Estate Company",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 14550000,
    durationAr: "10 أشهر",
    durationEn: "10 Months",
    startDate: "2021-06",
    completionDate: "2022-04",
    progress: 100,
    scopeAr: "توريد وتركيب أعمدة الإنارة وشبكات الكهرباء وتعبيد شوارع المخطط.",
    scopeEn: "Light poles & Road Works.",
    category: 'utility'
  },
  {
    id: 9,
    nameAr: "مشروع الأعمال الترابية بموقع شركة أسمنت الرياض",
    nameEn: "Earthworks Project at Riyadh Cement Company Site",
    clientAr: "شركة أسمنت الرياض",
    clientEn: "Riyadh Cement Company SJSC",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 8750000,
    durationAr: "6 أشهر",
    durationEn: "6 Months",
    startDate: "2021-10",
    completionDate: "2022-04",
    progress: 100,
    scopeAr: "أعمال حفر تكسير وتفكيك الصخور الثقيلة لخطوط الإنتاج وتوسعة المحجر.",
    scopeEn: "Stone Breaking Works.",
    category: 'excavation'
  },
  {
    id: 10,
    nameAr: "مشروع إنشاء شبكات وقنوات تصريف مياه الأمطار",
    nameEn: "Implementation of Rain water Drainage channels & Network",
    clientAr: "أمانة منطقة الرياض",
    clientEn: "Riyadh Municipality",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 19500000,
    durationAr: "سنة و 4 أشهر",
    durationEn: "1 Year, 4 Months",
    startDate: "2022-03",
    completionDate: "2023-07",
    progress: 100,
    scopeAr: "تنفيذ شبكات تصريف مياه السيول والأمطار في حيي النرجس والسلّي.",
    scopeEn: "Rainwater drainage networks in Al-Narjis & Al-Sulai Dist.",
    category: 'utility'
  },
  {
    id: 11,
    nameAr: "مشروع رسن طيبة في حي العزيزية",
    nameEn: "Rasen Taiba Project in Al-Aziziyah District",
    clientAr: "شركة رسن العقارية",
    clientEn: "Rasen Real Estate Company",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 7800000,
    durationAr: "10 أشهر",
    durationEn: "10 Months",
    startDate: "2022-01",
    completionDate: "2022-11",
    progress: 100,
    scopeAr: "تركيب شبكات الإسفالت، تركيب بلاط الأرصفة البلاط المتداخل، وأعمدة الإنارة الموفرة للطاقة.",
    scopeEn: "Asphalt, Sidewalks & Light Pole.",
    category: 'roads'
  },
  {
    id: 12,
    nameAr: "مشروع الإسفالت والمواقف لمجمع شركة أبل غرب مطار الملك خالد",
    nameEn: "Asphalt & Parking Project, Apple Area Building, West of King Khaled Airport",
    clientAr: "شركة نسما وشركاهم",
    clientEn: "Nesma & Partners",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 8750000,
    durationAr: "سنتان وشهرا تان",
    durationEn: "2 Year, 2 Months",
    startDate: "2021-01",
    completionDate: "2023-03",
    progress: 100,
    scopeAr: "تسوية منسوب الأرض، تعبيد مسارات الطرق وحرم المجمع، وإنشاء مواقف متكاملة.",
    scopeEn: "Land Leveling, Road Paving, & Parking Works.",
    category: 'roads'
  },
  {
    id: 13,
    nameAr: "مشروع الرياض أوتلت",
    nameEn: "Riyadh Outlet",
    clientAr: "شركة صلة",
    clientEn: "Sila Company",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 2350000,
    durationAr: "5 أشهر",
    durationEn: "5 Months",
    startDate: "2023-01",
    completionDate: "2023-06",
    progress: 100,
    scopeAr: "إزالة طبقات الأسفلت والمخلفات القديمة، ترحيل المواد والتسوية الترابية للموقع وإعادة الردم.",
    scopeEn: "Removal of Asphalt & Debris, Disposal of Materials, Earthworks & Backfilling of Materials.",
    category: 'excavation'
  },
  {
    id: 14,
    nameAr: "مشروع مخطط حي الربوة 720",
    nameEn: "Al Rabwa District, Plan Project 720",
    clientAr: "شركة عوائد للتطوير والاستثمار العقاري",
    clientEn: "Awaed Real Estate Development and Investment Company",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 7800000,
    durationAr: "10 أشهر",
    durationEn: "10 Months",
    startDate: "2022-08",
    completionDate: "2023-06",
    progress: 100,
    scopeAr: "الأعمال البنية التحتية الشاملة للمخطط السكني.",
    scopeEn: "Comprehensive Infrastructure Work for the Project.",
    category: 'infrastructure'
  },
  {
    id: 15,
    nameAr: "مشروع المنطقة اللوجستية المتكاملة غرب مطار الملك خالد",
    nameEn: "Logistics Zone Project West of King Khalid Airport in Riyadh",
    clientAr: "شركة نسما وشركاهم",
    clientEn: "Nesma & Partners",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 42850000,
    durationAr: "سنتان و 7 أشهر",
    durationEn: "2 Years, 7 Months",
    startDate: "2021-03",
    completionDate: "2023-10",
    progress: 100,
    scopeAr: "أعمال حفر وتسوية وقطع ترابي شامل وإزالة الأنقاض والصخور السطحية.",
    scopeEn: "Earthworks (excavation, removal of debris, and soil leveling).",
    category: 'infrastructure'
  },
  {
    id: 16,
    nameAr: "مخطط أجيليتي الصناعي بالرياض",
    nameEn: "Agility Industrial Plan",
    clientAr: "شركة أجيليتي",
    clientEn: "Agility Company",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 17355600,
    durationAr: "سنة و 7 أشهر",
    durationEn: "1 Year, 7 Months",
    startDate: "2022-04",
    completionDate: "2023-11",
    progress: 100,
    scopeAr: "أعمال الطرق المعبدة، شبكات الكهرباء والإنارة، شبكة المياه والصرف، ومكافحة الحريق للمخطط اللوجستي الدولي.",
    scopeEn: "Road Works, Electric Works, Drainage & Water system Works, Fire safety works.",
    category: 'utility'
  },
  {
    id: 17,
    nameAr: "مشروع الأعمال الترابية لطريق ماوان بالدلم",
    nameEn: "Earthworks Project at Mawan Road in Al-Dilam Governorate",
    clientAr: "الشركة الوطنية للتشييد والبناء",
    clientEn: "National Construction Company",
    locationAr: "الدلم / الدمام",
    locationEn: "Al-Dilam / Dammam",
    valueSAR: 6500000,
    durationAr: "9 أشهر",
    durationEn: "9 Months",
    startDate: "2023-04",
    completionDate: "2024-01",
    progress: 100,
    scopeAr: "أعمال الحفر والـقـطـع الصخري وإزالة ركام الرمال مع تسوية الطبقات الإسفلتية التمهيدية.",
    scopeEn: "Excavation, Debris Removal, Soil Levelling Works.",
    category: 'infrastructure'
  },
  {
    id: 18,
    nameAr: "مشروع السفلتة والأعمال الترابية في حي السلي",
    nameEn: "Asphalt & Earthworks Project in Al-Sulai",
    clientAr: "شركة أجيليتي",
    clientEn: "Agility Company",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 4850500,
    durationAr: "7 أشهر",
    durationEn: "7 Months",
    startDate: "2023-07",
    completionDate: "2024-02",
    progress: 100,
    scopeAr: "التمهيد الإنشائي وسفلتة البنية التحتية للطرق الفرعية.",
    scopeEn: "Earthwork & Asphalt Paving.",
    category: 'roads'
  },
  {
    id: 19,
    nameAr: "مشروع الديوان الملكي بقصر اليمامة",
    nameEn: "Royal Court",
    clientAr: "إدارة الشؤون الخاصة لسمو ولي العهد والقصر",
    clientEn: "Private Affairs of Royal Highness",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 9300000,
    durationAr: "سنة و 9 أشهر",
    durationEn: "1 Year, 9 Months",
    startDate: "2022-07",
    completionDate: "2024-04",
    progress: 100,
    scopeAr: "شبكة البنية التحتية، رصف المداخل والممرات وتعبيد الأسفلت الفاخر.",
    scopeEn: "Infrastructure & Paving Works.",
    category: 'infrastructure'
  },
  {
    id: 20,
    nameAr: "شبكة قنوات لتصريف مياه الأمطار والسيول",
    nameEn: "Stormwater & Rain water Drainage Network",
    clientAr: "شركة شبه الجزيرة للمقاولات (SAJCO)",
    clientEn: "Shibh Al Jazira Contracting Company (SAJCO)",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 12825500,
    durationAr: "3 سنوات و 6 أشهر",
    durationEn: "3 Year, 6 Months",
    startDate: "2021-02",
    completionDate: "2024-08",
    progress: 100,
    scopeAr: "أعمال حفر ونقل مخلفات وتسوية التربة لتمديد عبارات مائية ضخمة.",
    scopeEn: "Excavation, Debris Removal, Soil Levelling works.",
    category: 'utility'
  },
  {
    id: 21,
    nameAr: "مشروع حديقة العروبة الكبرى",
    nameEn: "Al-Urobah Park Project",
    clientAr: "شركة اليمامة للمقاولات",
    clientEn: "Al-Yamamah Contracting Company",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 12850700,
    durationAr: "سنة و 11 شهراً",
    durationEn: "1 Year, 11 Months",
    startDate: "2024-01",
    completionDate: "2025-12",
    progress: 100,
    scopeAr: "تمهيد الحديقة عبر أعمال قطع وردم وتسوية مناسيب التلال الاصطناعية وسفلتة مواقف السيارات المجاورة.",
    scopeEn: "Earthworks (excavation, removal of debris, soil leveling and asphalt paving).",
    category: 'infrastructure'
  },
  {
    id: 22,
    nameAr: "مواقف السيارات لمركز الملك عبد الله المالي (KAFD) - المرحلة أ",
    nameEn: "KAFD Car Parking (Phase A)",
    clientAr: "شركة ماركو (MARCO)",
    clientEn: "MARCO",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 9800500,
    durationAr: "سنة و 6 أشهر",
    durationEn: "1 Year, 6 Months",
    startDate: "2023-05",
    completionDate: "2024-11",
    progress: 100,
    scopeAr: "تنفيذ حفريات الأساسات العميقة للأقبية وسحب المياه الجوفية وترحيل المخلفات.",
    scopeEn: "Earthworks (excavation, removal of debris, Site cleaning).",
    category: 'excavation'
  },
  {
    id: 23,
    nameAr: "مواقف السيارات لمركز الملك عبد الله المالي (KAFD) - المرحلة ب",
    nameEn: "KAFD Car Parking (Phase B)",
    clientAr: "شركة ماركو (MARCO)",
    clientEn: "MARCO",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 6450000,
    durationAr: "8 أشهر",
    durationEn: "8 Months",
    startDate: "2024-07",
    completionDate: "2025-03",
    progress: 100,
    scopeAr: "أعمال تهيئة التربة، الحفر وتدبيش الجوانب لتأمين موقع المشروع.",
    scopeEn: "Earthworks (excavation, removal of debris, Site cleaning).",
    category: 'excavation'
  },
  {
    id: 24,
    nameAr: "مشروع حديقة الملك عبد الله الدولية",
    nameEn: "King Abdullah International Park Project",
    clientAr: "مجموعة زياد الحسين للمقاولات",
    clientEn: "Ziad al-Hussain Group Contracting Company",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 8788650,
    durationAr: "8 أشهر",
    durationEn: "8 Months",
    startDate: "2025-03",
    completionDate: "2025-11",
    progress: 100,
    scopeAr: "أعمال ترابية ضخمة، حفر الجيوديسية وتكسير الصخور وحرم المواقف الخارجي والسفلتة.",
    scopeEn: "Earthworks (excavation, removal of debris, soil leveling and asphalt paving).",
    category: 'infrastructure'
  },
  {
    id: 25,
    nameAr: "مشروع ليسن فالي",
    nameEn: "Laysen Valley Project",
    clientAr: "شركة دار الأعمال للمقاولات",
    clientEn: "Dar al-Amaal Contracting Company",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 11850600,
    durationAr: "سنة و 6 أشهر",
    durationEn: "1 Year, 6 Months",
    startDate: "2025-05",
    completionDate: "2026-11",
    progress: 100,
    scopeAr: "تمهيد الطرق وتجهيز البنية التحتية، شبكات تصريف المياه ورصف ممرات المشاة بمحيط المشروع الشهير.",
    scopeEn: "Earthworks (excavation, removal of debris, soil leveling and asphalt paving).",
    category: 'infrastructure'
  },
  {
    id: 26,
    nameAr: "حديقة حي الجزيرة",
    nameEn: "Al-Jazira Dist Park Project",
    clientAr: "مجموعة زياد الحسين للمقاولات",
    clientEn: "Ziad al-Hussain Group Contracting Company",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 4350750,
    durationAr: "قيد التشغيل والمتابعة",
    durationEn: "Still in work",
    startDate: "2026-02",
    completionDate: "قيد التنفيذ / In Progress",
    progress: 40,
    scopeAr: "أعمال حفريات الموقع، تسوية المناسيب الرملية، تحضير شبكة الطرق الداخلية والإنارة والمواقف.",
    scopeEn: "Earthworks (excavation, removal of debris, soil leveling and asphalt paving).",
    category: 'infrastructure'
  },
  {
    id: 27,
    nameAr: "مشروع فندق نوفوتيل (The Rosed)",
    nameEn: "The Rosed Project (NOVOTEL)",
    clientAr: "شركة صالح الراجحي للمقاولات",
    clientEn: "Saleh al-Rajhi Contracting Company",
    locationAr: "الرياض",
    locationEn: "Riyadh",
    valueSAR: 6800750,
    durationAr: "قيد التشييد حالياً",
    durationEn: "Still in Work",
    startDate: "2026-03",
    completionDate: "قيد التنفيذ / In Progress",
    progress: 15,
    scopeAr: "تنفيذ أعمال الحفر العميقة، تأمين جوانب الحفر الإنشائية، وتنظيف الموقع للأكتاف الأساسية وتجهيز سفلتة المداخل.",
    scopeEn: "Earthworks (excavation, removal of debris, soil leveling and asphalt paving).",
    category: 'excavation'
  }
];

export const equipmentList: Equipment[] = [
  { id: 1, nameAr: "جريدر (Grader)", nameEn: "Motor Grader", count: 18, category: 'heavy', icon: 'HardHat' },
  { id: 2, nameAr: "بلدوزر (Bulldozer)", nameEn: "Heavy Bulldozer", count: 16, category: 'heavy', icon: 'Construction' },
  { id: 3, nameAr: "شيول (Shovel / Loader)", nameEn: "Wheel Loader", count: 25, category: 'heavy', icon: 'LoaderPinpoint' },
  { id: 4, nameAr: "رصاصة ترابية (Soil Compactor)", nameEn: "Soil Roller Compactor", count: 25, category: 'heavy', icon: 'Zap' },
  { id: 5, nameAr: "بوبكات (Bobcat)", nameEn: "Skid Steer Loader", count: 12, category: 'heavy', icon: 'Cpu' },
  { id: 6, nameAr: "معدات شفط ومضخات غاطسة (Suction Pump)", nameEn: "Water Suction Pumps", count: 3, category: 'specialized', icon: 'Waves' },
  { id: 7, nameAr: "وايت مياه (Water Tanker)", nameEn: "Water Tanker Truck", count: 25, category: 'transport', icon: 'Truck' },
  { id: 8, nameAr: "تريلا وايت مياه (Trailer Water Tanker)", nameEn: "Heavy Water Trailer", count: 25, category: 'transport', icon: 'Container' },
  { id: 9, nameAr: "سيارات دبل قلاب 3م3 (Mini Dumper)", nameEn: "Concrete Dumper Trucks", count: 15, category: 'transport', icon: 'Truck' },
  { id: 10, nameAr: "مكنسة كنس شوارع (Sweeper)", nameEn: "Road Sweeper Broom", count: 2, category: 'specialized', icon: 'Wand' },
  { id: 11, nameAr: "مكسر خرسانة متنقل (Concrete Mixer)", nameEn: "Transit Mixer", count: 2, category: 'specialized', icon: 'Combine' },
  { id: 12, nameAr: "جي سي بي (JCB Backhoe)", nameEn: "JCB Backhoe Loader", count: 14, category: 'heavy', icon: 'Hammer' },
  { id: 13, nameAr: "كرين ونش (Truck Crane)", nameEn: "Boom Truck Crane", count: 6, category: 'heavy', icon: 'Wrench' },
  { id: 14, nameAr: "كرين تلسكوبي على كفرات (Tire Crane)", nameEn: "Mobile Crane", count: 3, category: 'heavy', icon: 'ShieldAlert' },
  { id: 15, nameAr: "بوكلين (Excavator)", nameEn: "Crawler Excavator", count: 55, category: 'heavy', icon: 'Shovel' },
  { id: 16, nameAr: "تريلا قلاب كبير (Heavy Dumper Trailer)", nameEn: "Muck Trailer Truck", count: 65, category: 'transport', icon: 'Truck' },
  { id: 17, nameAr: "قلاب 6 متر (Standard Dumper)", nameEn: "6-Cubic Meter Dumper", count: 45, category: 'transport', icon: 'Truck' },
  { id: 18, nameAr: "كسارة صخور ثنائية وثابتة (Crusher)", nameEn: "Stone Rock Crusher", count: 2, category: 'specialized', icon: 'Flame' },
  { id: 19, nameAr: "باصات نقل كوادر (Buses)", nameEn: "Staff Transport Buses", count: 3, category: 'transport', icon: 'Bus' },
  { id: 20, nameAr: "مركبات نقل مواد بيك آب (Pickups / Vans)", nameEn: "Vans & Support Vehicles", count: 14, category: 'transport', icon: 'Car' },
  { id: 21, nameAr: "حفارة خنادق جنزير (Trencher)", nameEn: "Chain Trenching Excavator", count: 1, category: 'heavy', icon: 'Layers' },
  { id: 22, nameAr: "مضخة خرسانة ذراع (Concrete Pump)", nameEn: "Concrete Boom Pump", count: 2, category: 'heavy', icon: 'Activity' },
  { id: 23, nameAr: "رافعة تلسكوبية (Telehandler)", nameEn: "Telehandler Forklift", count: 2, category: 'heavy', icon: 'Anchor' },
  { id: 24, nameAr: "رافعة شوكية (Forklift)", nameEn: "Industrial Forklift", count: 4, category: 'heavy', icon: 'CheckSquare' },
  { id: 25, nameAr: "كرين هيدروليكي (Hydraulic Crane)", nameEn: "Hydraulic Crane Truck", count: 3, category: 'heavy', icon: 'Settings' },
  { id: 26, nameAr: "رافعة برجية كهربائية (Tower Crane)", nameEn: "Tower Crane", count: 1, category: 'heavy', icon: 'Building' },
  { id: 27, nameAr: "لودر زاحف صغير (Skid Loader)", nameEn: "Mini Crawler Loader", count: 4, category: 'heavy', icon: 'Compass' },
  { id: 28, nameAr: "فرادة أسفلت مجنزرة (Asphalt Paver)", nameEn: "Asphalt Laying Machine", count: 1, category: 'heavy', icon: 'Gauge' },
  { id: 29, nameAr: "مولدات كهرباء كاتمة (Generator)", nameEn: "Silent Power Generators", count: 15, category: 'power', icon: 'Power' },
  { id: 30, nameAr: "رصاصة يدوية هزازة (Hand Compactor)", nameEn: "Vibratory Hand Roller", count: 13, category: 'heavy', icon: 'Activity' },
  { id: 31, nameAr: "كومبريشر هواء قوي (Air Compressor)", nameEn: "Pneumatic Air Compressor", count: 5, category: 'support', icon: 'Wind' },
  { id: 32, nameAr: "إضاءة أبراج ملاعب متنقلة (Light Tower)", nameEn: "Mobile Field Light Tower", count: 4, category: 'support', icon: 'Lightbulb' },
  { id: 33, nameAr: "وايت سحب شفط صحي (Vaccum Truck)", nameEn: "Sanitary Vacuum Tanker", count: 1, category: 'transport', icon: 'Worry' },
  { id: 34, nameAr: "مقطورة ناقلة وقود ديزل (Fuel Tanker)", nameEn: "Diesel Fuel Tank Trailer", count: 5, category: 'transport', icon: 'Database' },
  { id: 35, nameAr: "مضخات مياه متنقلة ديزل (Mobile Pump)", nameEn: "Diesel Mobile Water Pumps", count: 6, category: 'power', icon: 'Shuffle' }
];

export const orgChart: OrgNode = {
  titleAr: "رئيس مجلس الإدارة",
  titleEn: "Chairman of the Board",
  nameAr: "سفران سعود مسفر العتيبي",
  nameEn: "Safran Saud Misfer Al-Otaibi",
  children: [
    {
      titleAr: "الرئيس التنفيذي للشركة (C.E.O)",
      titleEn: "Chief Executive Officer (C.E.O)",
      nameAr: "عبدالعزيز سفران العتيبي",
      nameEn: "Abdulaziz Safran Al-Otaibi",
      children: [
        {
          titleAr: "نائب الرئيس للعمليات والمشاريع الميدانية (C.O.O)",
          titleEn: "VP of Operations & Site Projects (C.O.O)",
          nameAr: "المهندس / فهد سفران العتيبي",
          nameEn: "Eng. Fahad Safran Al-Otaibi",
          children: [
            {
              titleAr: "إدارة مشاريع البنية التحتية والمرافق",
              titleEn: "Infrastructure & Utilities Projects Division",
              children: [
                { titleAr: "قسم تمديد شبكات المياه والسيول وصمامات التحكم", titleEn: "Water & Torrent Networks Construction" },
                { titleAr: "قسم الصرف الصحي وتصريف مياه الأمطار والرفع الميكانيكي", titleEn: "Sewage, Rain Drainage & Lift Station Execution" },
                { titleAr: "قسم تمديد الكابلات وحفر الأنفاق المصغر والمسارات المغلقة", titleEn: "Cabling, Micro-Tunneling & Pipe Jacking Services" }
              ]
            },
            {
              titleAr: "إدارة مشاريع الطرق والتسويات والأسفلت",
              titleEn: "Roads, Earthworks & Asphalt Paving Division",
              children: [
                { titleAr: "قسم أعمال القطع الصخري والحفر والردم والتسويات الترابية", titleEn: "Rock Excavation, Backfilling, and Mass Grading" },
                { titleAr: "قسم سفلتة الطرق السريعة والشوارع وتثبيت التربة وتطوير التقاطعات", titleEn: "Highway Asphalt Laying, Soil Stabilization & Intersection Dev" },
                { titleAr: "قسم الأرصفة والبردورات والتخطيط واللوحات والسلامة المرورية", titleEn: "Curbing, Road Marking, Traffic Signage & Safety Systems" }
              ]
            },
            {
              titleAr: "إدارة الأسطول والمعدات والحركة واللوجستيات",
              titleEn: "Fleet Logistics, Machinery & Dispatching Dept",
              children: [
                { titleAr: "وحدة جدولة وتوزيع وصيانة مسارات الآليات الثقيلة", titleEn: "Heavy Machinery Scheduling, Dispatching & Routing" },
                { titleAr: "وحدة تزويد الوقود والديزل المتنقلة وصهاريج الدعم الميداني", titleEn: "Mobile Fuel & Diesel Tankers & On-site Support" },
                { titleAr: "قسم المستودعات المركزية وقطع الغيار والزيوت والإطارات", titleEn: "Central Warehouses, Spare Parts, Oils & Tires Inventory" }
              ]
            },
            {
              titleAr: "إدارة الصيانة الهندسية والورش الفنية الفورية",
              titleEn: "Technical Maintenance & Rapid Repair Workshops",
              children: [
                { titleAr: "ورشة الأعطال الميكانيكية الثقيلة والمحركات والتوضيب", titleEn: "Heavy Mechanical Repair Plant, Overhauls & Engines" },
                { titleAr: "فريق الطوارئ والصيانة والإنقاذ الميداني المتنقل", titleEn: "Mobile Site Rescue, Field Welders & Rapid Support" },
                { titleAr: "قسم الكهرباء والهيدروليك وتشخيص الأعطال بالكمبيوتر", titleEn: "Hydraulics, Electrical Fleet Diagnostics & Calibration" }
              ]
            },
            {
              titleAr: "إدارة السلامة والصحة المهنية والمخاطر والبيئة (HSE)",
              titleEn: "Health, Safety, Risk Management & Environment (HSE)",
              children: [
                { titleAr: "مفتشو وضباط السلامة والوقاية الميدانيين بالمشاريع", titleEn: "Certified Site Safety Officers, Inspectors & Auditors" },
                { titleAr: "مراقبة الأثر البيئي وإدارة الفضلات الإنشائية وإعادة التدوير", titleEn: "Environmental Impact, Construction Waste & Recycling" },
                { titleAr: "قسم التدريب الوقائي المستمر ومحاكاة الطوارئ الموقعية", titleEn: "HSE Training Academy, Site Induction & Emergency Drills" }
              ]
            }
          ]
        },
        {
          titleAr: "المدير الفني العام ورئيس المكتب الهندسـي (C.T.O)",
          titleEn: "Chief Technical Officer & Engineering Head (C.T.O)",
          children: [
            {
              titleAr: "المكتب الفني المركزي والدراسات والرسومات التفصيلية",
              titleEn: "Central Technical Office, Studies & Shop Drawings",
              children: [
                { titleAr: "قسم دراسة التصاميم الهندسية ومطابقتها للمواصفات", titleEn: "Design Analysis & Engineering Specifications Review" },
                { titleAr: "قسم حصر كميات المواد التفصيلية وإعداد جداول الأسعار والفوترة", titleEn: "Detailed Quantity Surveying (QS) & Bill of Quantities" },
                { titleAr: "مخططات الورشة التنفيذية والمخططات كما نفذت والمقاطع العرضية", titleEn: "Shop Drawings, Profile Alignments, and As-Built Dossiers" }
              ]
            },
            {
              titleAr: "إدارة توكيد وجودة الإنشاءات والمختبرات (QA/QC)",
              titleEn: "Quality Assurance, Quality Control & Labs Division",
              children: [
                { titleAr: "مختبر فحص جودة وصلاحية التربة والخرسانة المسلحة والأسفلت", titleEn: "Soil Mechanics, Concrete & Asphalt Material Laboratories" },
                { titleAr: "قسم اعتماد المواد ومطابقتها لمقاييس وتصنيفات وزارة النقل والبلديات", titleEn: "Materials Submittal Approval & MOT/MOMRA Standards Compliance" },
                { titleAr: "قسم التفتيش الميداني وأخذ العينات العشوائية وتقييم متانة الإنشاءات", titleEn: "Field Inspections, Random Sampling & Core-Testing Audits" }
              ]
            },
            {
              titleAr: "إدارة المساحة والجيوديسيا والخرائط ونظم المعلومات الجغرافية",
              titleEn: "Land Surveying, Geodetic Services & GIS Department",
              children: [
                { titleAr: "فرق المسح الطبوغرافي وتحديد مسارات الطرق والمحاور", titleEn: "Topographic Surveying, Alignment Control & Baseline Teams" },
                { titleAr: "وحدة رصد الإحداثيات والشبكات عبر الأقمار الصناعية (GPS/RTK)", titleEn: "Satellite Geodetic Networks & Dual-Frequency GPS Systems" },
                { titleAr: "رسم الخرائط الكنتورية والرفع الميداني وحساب الحجوم الهندسية للقطع والردم", titleEn: "Contour Mapping, Cut/Fill Volumes & GIS Software Integration" }
              ]
            }
          ]
        },
        {
          titleAr: "المدير المالي التنفيذي وتطوير العقود والاستثمارات (C.F.O)",
          titleEn: "Chief Financial Officer & Contract Strategy (C.F.O)",
          children: [
            {
              titleAr: "إدارة الحسابات العامة والتدقيق المالي والخزينة",
              titleEn: "General Accounting, Financial Audit & Treasury Dept",
              children: [
                { titleAr: "قسم المستخلصات المالية للجهات الحكومية والخاصة والتدفقات النقدية", titleEn: "Governmental & Private Project Invoicing, Progress Claims & Cashflow" },
                { titleAr: "المراجعة الداخلية والمحاسبة الضريبية والزكوية والرواتب والامتثال", titleEn: "Internal Audit, Zakat/Income Tax, Payroll Systems (WPS)" },
                { titleAr: "إدارة حسابات المصارف والتسهيلات البنكية والاعتمادات والضمانات", titleEn: "Banking Services, Corporate Facilities, Guarantees & LCs" }
              ]
            },
            {
              titleAr: "إدارة العقود والمناقصات والتسعير والتقدير المالي",
              titleEn: "Contracts, Tenders, Estimations & Pricing Dept",
              children: [
                { titleAr: "دراسة كراسات الشروط والمواصفات للمشاريع الحكومية العملاقة", titleEn: "RFP Analysis, Scope Evaluation & Mega-Project Bidding" },
                { titleAr: "قسم دراسات الجدوى وتكلفة المشاريع والتمويل الرأسمالي والتسعير المالي", titleEn: "Feasibility Studies, Direct/Indirect Costing & Strategic Pricing" },
                { titleAr: "صياغة وتدقيق عقود مقاولي الباطن والشركاء وموردي الكتل والمواد", titleEn: "Subcontractor Agreements, Joint Ventures & Material Contracts" }
              ]
            },
            {
              titleAr: "إدارة المشتريات العامة وسلاسل الإمداد اللوجستية وتوريد المواد",
              titleEn: "Corporate Procurement & Materials Supply Chain",
              children: [
                { titleAr: "قسم شراء الإسمنت والخرسانة والأسفلت والحديد والكتل الإنشائية", titleEn: "Aggregates, Ready-mix Concrete, Bitumen & Reinforcement Sourcing" },
                { titleAr: "إدارة علاقات الموردين وتأهيل الكسارات والمصانع المعتمدة للتوريد", titleEn: "Vendor Relationship Management & Quarry/Plant Accreditations" },
                { titleAr: "وحدة استئجار وتأمين المعدات التخصصية والمولدات والآليات النادرة", titleEn: "Specialized Machinery Rent, Ancillary Tools & Support Operations" }
              ]
            }
          ]
        },
        {
          titleAr: "مدير الشؤون الإدارية والموارد البشرية والعلاقات الحكومية",
          titleEn: "Executive Director of HR & Support Services",
          children: [
            {
              titleAr: "إدارة شؤون الموظفين ورأس المال البشري والتدريب",
              titleEn: "Human Capital, Personnel & Workforce Management",
              children: [
                { titleAr: "التوظيف المحلي والاتفاقيات الدولية ومكتب استقدام العمالة الفنية والمهندسين", titleEn: "Local Recruitment, Global Sourcing & Visa Processing for Technical staff" },
                { titleAr: "قسم التأمينات الاجتماعية وبطاقات الموظفين والتأمين الطبي وحماية الأجور (GOSI)", titleEn: "GOSI Compliance, Medical Insurance & Wage Protection Alignment" },
                { titleAr: "خدمات شؤون الإقامات والعمل والبلديات ومكتب العمل السعودي (قوى ومقيم)", titleEn: "Saudi Labor Platforms (Qiwa, Muqeem) & Work Permit Administration" }
              ]
            },
            {
              titleAr: "إدارة العلاقات العامة والمتابعة الحكومية والاتصال المؤسسي (PR)",
              titleEn: "Public Relations, Government Affairs & Utilites Liaison",
              children: [
                { titleAr: "قسم استخراج رخص الحفر بالبلديات وتصاريح قطوعات الطرق والتحويلات المرورية", titleEn: "Municipal Excavation Permits, Street Cuts & Traffic Detour Approvals" },
                { titleAr: "التنسيق التقني مع الجهات الخدمية والوزارات والجهات المالكة للمرافق القائمة", titleEn: "Utilities Coordination Liaison (Saudi Electricity, NWC, Telecom, Municipalities)" },
                { titleAr: "المسؤولية الاجتماعية والاتصال المؤسسي واللوحات والتمثيل الرسمي للمجموعة", titleEn: "Corporate Social Responsibility, Branding, Public Notices & Official Representation" }
              ]
            },
            {
              titleAr: "إدارة الشؤون القانونية والعقود العامة والامتثال التنظيمي",
              titleEn: "Legal Department, Contract Governance & Compliance",
              children: [
                { titleAr: "صياغة ودراسة اللوائح والأنظمة الداخلية وضوابط حوكمة الشركات السعودية", titleEn: "Drafting Corporate Bylaws, Board Resolutions & Saudi Companies Law Alignment" },
                { titleAr: "التحكيم الفني، المراجعة العقدية، فض النزاعات الهندسية وتسوية القضايا", titleEn: "Technical Arbitration, Contractual Dispute Resolutions & Labor Audits" },
                { titleAr: "متابعة امتثال الشركة للمتطلبات واللوائح السعودية الحديثة وهيئة المقاولين", titleEn: "SCA Compliance Monitoring, Quality Standard Licenses & Saudi Regulations" }
              ]
            },
            {
              titleAr: "إدارة تكنولوجيا المعلومات والنظم والتحول الرقمي والأتمتة (IT)",
              titleEn: "Information Technology, ERP & Digital Infrastructure",
              children: [
                { titleAr: "أنظمة تخطيط موارد المؤسسة المتكاملة (ERP) وبرامج إدارة المشاريع الإنشائية الميدانية", titleEn: "Unified Corporate ERP Implementation & Field Construction Project Software" },
                { titleAr: "شبكات الاتصالات اللاسلكية والربط الفضائي الآمن بين المواقع الميدانية والإدارة العامة", titleEn: "Secure Site-to-HQ Wireless Communication Networks & Telemetry" },
                { titleAr: "الدعم الفني، الأمن السيبراني وحماية البيانات وتراخيص البرامج والنمذجة (BIM/CAD)", titleEn: "Cybersecurity, Backups, Workstations Support & Engineering CAD/BIM Licensing" }
              ]
            }
          ]
        }
      ]
    }
  ]
};

export const dict = {
  ar: {
    title: "شركة دار السالمية للمقاولات",
    subtitle: "رائـدون في البنية التحتية وتسوية المواقع ورصف الطرق منذ عام 1979م",
    about: "من نحن",
    services: "خدماتنا المتخصصة",
    projects: "مشاريعنا المنفذة",
    fleet: "أسطول المعدات الثقيلة",
    clients: "عملاؤنا وشركاؤنا",
    orgStructure: "الهيكل التنظيمي",
    contact: "اتصل بنا",
    langToggle: "English Portal",
    certified: "سجل تجاري سعودي رسمي معتمد من وزارة التجارة برأس مال مصرح",
    establishedYear: "1979",
    yearsOfExp: "أكثر من 47 سنة من الخبرة",
    experience: "الخبرة المكتسبة",
    crDescription: "تأسست شركة دار السالمية للمقاولات في مدينة الرياض عام 1979م، وهي إحدى الكيانات الوطنية الرائدة التي وضعت القواعد الأساسية لإنشاء وتطوير شبكات البنية التحتية والبيئة العمرانية في المملكة العربية السعودية على مدى أكثر من أربعة عقود.",
    missionTitle: "مهمتنا",
    missionDesc: "تنفيذ الأعمال المسندة إلينا بأعلى درجات المصداقية والحرفية المهنية العالية، وفق أحدث الأساليب والتقنيات الهندسية، وبالمواصفات المطلوبة وفي الوقت الزمني المحدد وبكل دقة.",
    visionTitle: "رؤيتنا وقيمنا",
    visionDesc: "تنفيذ أعمال وطنية ذات قيمة نوعية تسهم بأثر ملموس في تعزيز جودة البنية التحتية ورفع كفاءتها اللوجستية والاقتصادية بما يتواكب مع رؤية المملكة 2030.",
    pillarsTitle: "ركائز الثقة لدى عملائنا",
    pillarsDesc: "لم يكن النجاح صدفة، بل بني بالتعب والإخلاص المتبادل مع أهم الجهات الحكومية والشركات القيادية في القطاع الخاص، مستنداً إلى معايير صارمة للسلامة والجودة وبإدارة علمية مميزة.",
    p1Title: "الموثوقية والأمانة",
    p1Desc: "إخلاص وتفاني إدارتنا وفرقنا الميدانية يقدم صورة حقيقية وعلاقات شراكة طويلة الأجل أساسها الثقة والالتزام المطلق.",
    p2Title: "رأس المال البشري",
    p2Desc: "ندعم العنصر البشري ونطبق أعلى المعايير لسلامة عمالنا ومهندسينا، مما يشكل أهم ركائز النجاح المستدام لدينا.",
    p3Title: "الكفاءة الميدانية",
    p3Desc: "نمتاز بالجهوزية الميدانية عبر امتلاك وتأجير أحدث آليات الحفريات ومعدات الطرق الثقيلة ومساندة المشاريع الإستراتيجية.",
    servicesSubtitle: "باقة متكاملة من الحلول الهندسية المدنية والصناعية المعتمدة بالكامل",
    service1: "تسوية وتمهيد المواقع",
    service1Desc: "أعمال الكشط الإسفلتي وحفر المناسيب وتسوية التمور والوديان ونقل الأنقاض وتطهير الأراضي الإستراتيجية للمشروعات الفندقية والسكنية والتجارية.",
    service2: "أعمال البنية التحتية",
    service2Desc: "تجهيز البنى التحتية الشاملة للمناطق السحابية السكنية واللوجستية والصناعية ومناطق المطارات الدولية والمستودعات العملاقة والمحاجر صلبة التضاريس.",
    service3: "الطرق والأرصفة والإنارة",
    service3Desc: "رصف الشرايين الأساسية وتعبيد الأسفلت وفق كود البناء واشتراطات وزارة النقل والمشهد الحضري، تركيب البلاط المتداخل، والبردورات، وأعمدة الإنارة الموفرة.",
    service4: "شبكات التصريف والسيول",
    service4Desc: "حفر وتمديد قنوات تصريف مياه الأمطار والدرء وصنع عبارات خرسانية ضخمة وشبكات تمديد الصرف الصحي المتطورة في الأحياء الحديثة والبلدات.",
    service5: "تمديدات المياه والبيئة",
    service5Desc: "شق وتمديد خطوط المياه والمحابس العملاقة وصيانة الأنابيب الحاملة للتدفقات، وأعمال تهذيب مجاري السيول وتجريف الوديان المائية والبيئية غرب وشرق الرياض.",
    service6: "الشبكات والمساندة الفنية",
    service6Desc: "تمديد شبكات الجهد العالي والمنخفض والألياف وصنع غرف محطات الخدمة وعزل الكابلات وتنفيذ المخططات الهندسية لشركاء الدفاع والتطوير العقاري.",
    fleetSubtitle: "أحد أكبر الأساطيل الوطنية المساندة للمشاريع الكبرى بأكثر من 400 آلية ومعدة مجهزة بالكامل وتعمل بكفائة عالية في شتى مناطق المملكة",
    projectsSubtitle: "استعرض أكثر من 25 مشروعاً وطنياً إستراتيجياً تم إنجازها بنسبة نجاح 100% وبقيمة إجمالية تجاوزت مئات الملايين من الريالات السعودية",
    totalFleetCount: "إجمالي الأسطول المسجل",
    filterPlaceholder: "ابحث عن معدة محددة...",
    searchProject: "ابحث باسم المشروع أو العميل أو الموقع...",
    filterAll: "الكل",
    projLabelValue: "قيمة العقد",
    projLabelClient: "العميل / المالك",
    projLabelDuration: "مدة المشروع",
    projLabelDates: "الفترة الزمنية",
    projLabelLocation: "الموقع الجغرافي",
    contactUsTitle: "تواصل معنا - طلب عرض سعر",
    contactUsDesc: "اتصل بقسم المشاريع والتقديرات بشكل مباشر للحصول على عروض أسعار موثقة أو عقود تضامن واستشارات هندسية سريعة.",
    addressLabel: "العنوان البريدي والمكتب الرئيسي",
    addrDetails: "الرياض - شارع الإمام أبي حنيفة، ص.ب 150889 الرياض 11757، المملكة العربية السعودية",
    phoneLabel: "الهواتف الأرضية",
    mobileLabel: "جوال الإدارة المهندس المختص",
    emailLabel: "البريد الإلكتروني للشركات والمناقصات",
    officeHours: "ساعات العمل الرسمية",
    officeHoursVal: "السبت - الخميس: 8:00 صباحاً حتى 5:00 مساءً",
    formName: "اسم الشركة / الجهة الطالبة",
    formContact: "اسم الشخص المعني للاتصال",
    formEmail: "البريد الإلكتروني للتواصل الرسمي",
    formPhone: "رقم الجوال النشط (مثال: 050xxxxxxx)",
    formServiceType: "الخدمة المطلوبة الرئيسية",
    formBudget: "الميزانية المقدرة للمشروع (ريال سعودي)",
    formNeeds: "تفاصيل المشروع والاحتياجات الهندسية بدقة",
    formSubmit: "إرسال الطلب بشكل رسمي",
    pricingSuccess: "شكراً لتواصلكم مع شركة دار السالمية للمقاولات. تم استلام طلبكم برقم تذكرة #SAL-491 وبنجاح. سيقوم قسم العقود والمناقصات الهندسية بمراجعة ملفك والاتصال بك خلال 24 ساعة عمل.",
    backToHome: "الرجوع للرئيسية",
    footerText: "جميع الحقوق محفوظة © شركة دار السالمية للمقاولات ومسجلة رسمياً بالملكية الفكرية والعلامة التجارية. المملكة العربية السعودية 2026.",
    fleetCategoryAll: "جميع الفئات",
    fleetCategoryHeavy: "آليات ومعدات ثقيلة",
    fleetCategoryTransport: "نقليات شحن وصهاريج",
    fleetCategorySpecialized: "معدات متخصصة ومصانع",
    fleetCategorySupport: "معدات مساندة وإضاءة",
    fleetCategoryPower: "طاقة ومضخات توليد",
    viewChart: "استعراض شجرة الهيكل التنظيمي",
    orgChartDesc: "الهيكل الإداري الفعال الذي يضمن سلاسة اتخاذ القرار ومراقبة الصحة والسلامة المهنية ومطابقة معايير الجودة النوعية لعملائنا.",
    quoteTitle: "احصل على عرض سعر لخدمات المقاولات والآليات فوراً",
    projectCategoryAll: "جميع المشاريع",
    projectCategoryRoads: "أعمال الطرق والأسفلت",
    projectCategoryInfra: "أعمال البنية التحتية",
    projectCategoryExcavation: "أعمال التمهيد والحفريات",
    projectCategoryUtility: "شبكات التصريف والمرافق",
    crInfo: "شهادة السجل التجاري والبيانات المقيدة لفرع الشركة الرئيسي بالرياض",
    legalStatus: "كيان معتمد لتنفيذ كافة الأعمال الهندسية وشق الطرق والبنية التحتية وتمديدات المياه بالتصنيف والامتياز الوطني.",
    fleetCountLabel: "عدد الوحدات المتوفرة",
    activeStatus: "نشطة وجاهزة للخدمة"
  },
  en: {
    title: "Dar AL-Salmiah Contracting Co.",
    subtitle: "Pioneering Infrastructure, Site Leveling, and Road Construction Since 1979",
    about: "About Us",
    services: "Specialized Services",
    projects: "Our Projects Portfolio",
    fleet: "Heavy Machinery Fleet",
    clients: "Key Partners & Clients",
    orgStructure: "Organizational Structure",
    contact: "Contact Us",
    langToggle: "البوابة العربية",
    certified: "Official Saudi Commercial Registration Certified by the Ministry of Commerce with Paid Capital",
    establishedYear: "1979",
    yearsOfExp: "Over 47 Years of Experience",
    experience: "Acquired Experience",
    crDescription: "Dar AL-Salmiah Contracting Co. was established in Riyadh in 1979. It stands as one of the elite Saudi national entities that laid down foundational standards for constructing and improving robust infrastructure networks and real-estate terrains in the Kingdom for over four decades.",
    missionTitle: "Our Mission",
    missionDesc: "To deliver contracted projects in supreme compliance with modern engineering conventions, ensuring highest-tier reliability, professionalism, required specifications, exact standards, and prompt scheduled execution.",
    visionTitle: "Our Vision & Values",
    visionDesc: "To develop high-quality, high-return infrastructure solutions that substantially advance the logistic and economic framework of the Kingdom, actively contributing to Saudi Vision 2030 objectives.",
    pillarsTitle: "Pillars of Client Trust",
    pillarsDesc: "Our success is driven by professional devotion, building long-standing alignments with key Government ministries and leading private contractors, certified by severe safety and rigorous quality management.",
    p1Title: "Integrity & Trustworthiness",
    p1Desc: "Our management's absolute commitment and field teams' craftsmanship deliver trustworthy outcomes, reinforcing perennial partnerships.",
    p2Title: "Human Safeguards",
    p2Desc: "We actively prioritize on-site welfare, maintaining premium HSE systems for our technicians, engineers, and workforce.",
    p3Title: "Field Readiness",
    p3Desc: "Possessing an immense array of over 400 active massive assets enables lightning mechanical deployment for strategic tenders.",
    servicesSubtitle: "A Comprehensive, Pre-Qualified Suite of Civil and Industrial Engineering Solutions",
    service1: "Site Grading & Excavations",
    service1Desc: "Asphalt stripping, subgrade contouring, leveling dunes, debris removal, and clearing critical lands for hospitality, residential, and complex commercial hubs.",
    service2: "Mega Infrastructure Solutions",
    service2Desc: "Comprehensive grading and infrastructure setup for heavy logistics parks, residential sectors, industrial zones, international airports, and complex mines.",
    service3: "Roads, Paving & Urban Artistry",
    service3Desc: "Constructing arterial highways and paving roads in alignment with Ministry of Transport specifications. We install sidewalks, interlocking tiles, curbstones, and eco-friendly lighting.",
    service4: "Storm & Waste Water Networks",
    service4Desc: "Deep trenching, installing vast structural storm pipelines, box culverts, and advanced municipal sewerage system trunks in newly designed city sectors.",
    service5: "Water Distribution & Marine Ecology",
    service5Desc: "Installing massive water main headers, gate valves, and managing fluid pipelines. Handled deep valley re-channeling and flood-defense rock armor works in Riyadh.",
    service6: "Technical Grids & Grid Support",
    service6Desc: "Laying high & low voltage grids, fiber optical canals, constructing sub-stations, isolating cable lines, and fulfilling precision projects for defense and real estate partners.",
    fleetSubtitle: "One of Saudi Arabia's Largest National Heavy Asset Fleet with Over 400 Fully-Owned Active Machinery Units Ready for Rapid Deployment",
    projectsSubtitle: "Explore over 25 strategic national projects executed in 100% compliance with client specifications, valued at hundreds of millions of Saudi Arabian Riyals (SAR).",
    totalFleetCount: "Total Registered Fleet",
    filterPlaceholder: "Search for specific machinery...",
    searchProject: "Search by project, client, or location...",
    filterAll: "All",
    projLabelValue: "Contract Value",
    projLabelClient: "Client / Owner",
    projLabelDuration: "Execution Duration",
    projLabelDates: "Active Period",
    projLabelLocation: "Geographical Location",
    contactUsTitle: "Get in Touch - Request a Quote",
    contactUsDesc: "Contact our commercial estimates department directly to obtain formal quotations, join-venture treaties, or brief technical engineering consultancies.",
    addressLabel: "Postal Address & HQ Location",
    addrDetails: "Riyadh - Imam Abi Hanifah St, P.O. Box 150889 Riyadh 11757, Kingdom of Saudi Arabia",
    phoneLabel: "Phone Numbers",
    mobileLabel: "Direct General Mobile & WhastApp",
    emailLabel: "Corporate Inquiries & Tender Email",
    officeHours: "Official Work Hours",
    officeHoursVal: "Saturday - Thursday: 8:00 AM to 5:00 PM",
    formName: "Company / Requester Name",
    formContact: "Point of Contact Person",
    formEmail: "Official Communication Email",
    formPhone: "Active Contact Mobile (e.g., 05xxxxxxxx)",
    formServiceType: "Primary Service Category Requested",
    formBudget: "Project Estimated Budget (SAR)",
    formNeeds: "Project Scope & Mechanical Requirements Needed",
    formSubmit: "Submit Quotation Request",
    pricingSuccess: "Thank you for reaching out to Dar AL-Salmiah Contracting Co. Your request has been successfully registered under ticket #SAL-491. Our engineering contracts department will evaluate your scope and contact you within 24 business hours.",
    backToHome: "Return to Main Portal",
    footerText: "All Rights Reserved © Dar AL-Salmiah Contracting Co. Officially Registered and Trademarked. Kingdom of Saudi Arabia 2026.",
    fleetCategoryAll: "All Categories",
    fleetCategoryHeavy: "Heavy Bulldozers & Earthmovers",
    fleetCategoryTransport: "Transport Tankers & Dumper Trucks",
    fleetCategorySpecialized: "Specialized Concrete & Process Gear",
    fleetCategorySupport: "Support Equipment & Light Towers",
    fleetCategoryPower: "Generators & Submersible Pumps",
    viewChart: "View Organizational Structure Tree",
    orgChartDesc: "An advanced administrative layout ensuring swift, quality-controlled, and safety-rigorous dispatch of operations.",
    quoteTitle: "Get Instant Quote for Contracting & Equipment Rental",
    projectCategoryAll: "All Projects",
    projectCategoryRoads: "Road Paving & Asphalt",
    projectCategoryInfra: "Infrastructure Works",
    projectCategoryExcavation: "Deep Excavations & Prep",
    projectCategoryUtility: "Stormwater & Piping Grids",
    crInfo: "Official Commercial Registration and Riyadh HQ Credentials",
    legalStatus: "Fully licensed legal national body certified to perform all forms of general building, heavy excavation, asphalt paving, road construction, water piping, and mechanical solutions.",
    fleetCountLabel: "Available Units Fleet",
    activeStatus: "Operational & Field Ready"
  }
};
